### ISSUE TITLE
develop user 페이지 관련.

### ISSUE THREAD

**Issue by J-hokyun** [Aivle-4th-Team-16/big-project#50]
user sub_navbar를 상속받아서 user페이지 구현했는대 sub_navbar가 너무 커서 그런지 네비게이션 글씨들이 세로로 되어있습니다!
해결해주세용 😭 
<img width="1724" alt="navbar image" src="https://github.com/Aivle-4th-Team-16/big-project/assets/104821475/a0a33113-ff07-48fa-bbba-91d4f6765706">

**Comment by foreverfl** [comment]
그림이 안보여요 ㅠㅠ 제가 디자인 잡는다고 수정했는데.. 이따가 확인해볼게요.

**Comment by J-hokyun** [comment]
아마 develop에서 풀리퀘스트 하면 충돌날탠대 그냥 제가 만든걸로 다 갈아끼우면 됩니당 유저 페이지는 다완성되었고 자잘한 오류만 수정하면될거가탕요

**Comment by foreverfl** [comment]
넵 호균님꺼 중심으로 바꾸고, 디자인 잡고 돌아가는 식으로 머지해놓을게여

**Comment by foreverfl** [comment]
해결했습니다.
