### ISSUE TITLE
[user 페이지] 수정하기 안됨요

### ISSUE THREAD

**Issue by P-uyoung** [Aivle-4th-Team-16/big-project#68]

**Comment by J-hokyun** [comment]
로컬의 S3버킷에 user_images 폴더가있나요? 만약 있다면
이미지 업로드 이후에 user_images 폴더에서 이미지가 바뀌나 확인하여 주시고 그래도 안되면 내일말해주세여
<img width="914" alt="스크린샷 2024-01-03 오후 11 00 00" src="https://github.com/Aivle-4th-Team-16/OD/assets/104821475/18e6fbf1-5ada-4046-9e56-6d39a47f20dd">

**Comment by J-hokyun** [comment]
그 명규님이 지금은 테스트 단계여서 로컬에서 다른 팀원들이 테스트 할 수 있도록 로컬 파일경로로 해놓았고 우영님 AWS 경로로 설정은 안해놓았습니다. 지금 코드에서는 AWS 경로로 해놓으면 안되는게 맞구 오후에 가서 이야기해본다음에 AWS 경로로 바꿔보겠습니다.
